config/routes.rb
Rails.application.routes.draw do
  get 'attractions/homePage'
  
  get 'attractions/index'

  get 'attractions/new'

  get 'attractions/create'

  get 'attractions/update'

  get 'attractions/edit'

  get 'attractions/show'
 
  

  resources :attractions
  root :to => redirect('/attractions/homePage')
end

app/models/attraction.rb
class Attraction < ActiveRecord::Base
    def self.all_ratings ; %w[1 2 3 4 5] ; end
    validates :name, :presence => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/attractions_controller.rb
class AttractionsController < ApplicationController
  def index
    if params[:search_form]
       search = params[:search_form]
       @attractions = Attraction.where('name like ?', "%#{search}%")
    else
      @attractions = Attraction.all
    end
  end

  def new
      @attraction = Attraction.new
  end

  def create
    @attraction = Attraction.create(attraction_params)
    if @attraction.save
      flash[:notice] = "#{@attraction.name} was successfully created."
      redirect_to attractions_path
    else
      render 'new'
       flash[:notice] = "Cannot be created."
    end 
  end

  def attraction_params
    params.require(:attraction).permit(:name, :description, :rating, :entry, :web)
  end
  
  def update
    @attraction = Attraction.find params[:id]
    @attraction.update_attributes(attraction_params)
    if @attraction.save
      flash[:notice] = "#{@attraction.name} was successfully updated"
      redirect_to attraction_path(@attraction)
    else
      render 'edit'
      flash[:notice] = "Cannot be updated"
    end  
  end

  def edit
       @attraction = Attraction.find params[:id]
  end

  def show
      id = params[:id]
      @attraction = Attraction.find(id)
  end
  def destroy
    @attraction = Attraction.find(params[:id])
    @attraction.destroy
    flash[:notice] = "Attraction '#{@attraction.name}' was successfully deleted."
    redirect_to attractions_path
  end
  
  def homePage
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attractions_helper.rb
module AttractionsHelper
end

app/views/attractions/_attraction_form.html.haml
- unless @attraction.errors.empty?
  #warning
    Errors prevented this movie from being #{controller.action_name}d:
    %ul
      - @attraction.errors.full_messages.each do |error|
        %li= error
= label :attraction, :name, 'Name'
= text_field :attraction, :name
= label :attraction, :description, 'Description'
= text_field :attraction, :description
= label :attraction, :rating, 'Rating'
= select :attraction, :rating, Attraction.all_ratings
= label :attraction, :entry, 'Entry'
= text_field :attraction, :entry
= label :attraction, :web, 'Web'
= text_field :attraction, :web

app/views/attractions/create.html.haml
<h1>Attractions#create</h1>
<p>Find me in app/views/attractions/create.html.erb</p>

app/views/attractions/edit.html.haml
<h1>Edit Attraction
%h2
= form_tag attraction_path(@attraction), :method => :put do
  = render :partial => 'attraction_form'
  = submit_tag 'Save Changes'

app/views/attractions/homePage.html.haml
%h1 Pavan Kumar  Devineni

%h2 Cool Facts
%p Being Friendly With Everyone
%p Always Smiling

Click the link below that navigates to List of Attractions
%br
= link_to 'Index Page',attractions_index_path
<br/>
<br/>

app/views/attractions/index.html.haml
%h1 All Attractions
= form_tag '/attractions', :method => :get do
  = text_field_tag :search_form, params[:search_form]
  = submit_tag 'Search Attractions'
%table#attractions
  -if @attractions.presence
    %thead
      %tr
        %th Name
        %th Description
        %th Rating
        %th Entry
        %th Web
        %th More Info
    %tbody
      - @attractions.each do |attraction|
        %tr
          %td= attraction.name
          %td= attraction.description
          %td= attraction.rating
          %td= attraction.entry
          %td= attraction.web
          %td= link_to "More about #{attraction.name}", attraction_path(attraction)
  -else
    %b "Your Search Returned no results"
%br
= link_to 'Home Page',attractions_homePage_path
= link_to 'Add New Attraction', new_attraction_path

app/views/attractions/new.html.haml
%h1 Add New Attraction

= form_tag attractions_path, :method => :post do
  = render :partial => 'attraction_form'
  = submit_tag 'Save Changes'

app/views/attractions/show.html.haml
%h1 Attraction Details
%i Details about #{@attraction.name}
%ul#details
    %li 
        %b Description:
        = @attraction.description
    %li 
        %b Rating:
        = @attraction.rating
    %li 
        %b Entry:
        = @attraction.entry
    %li
        %b Web:
        = @attraction.web
    =link_to 'Edit Attraction', edit_attraction_path(@attraction)
    =link_to 'Delete Attraction', attraction_path(@attraction), :method => :delete
    =link_to 'Back To Attraction List', attractions_path

app/views/attractions/update.html.haml
<h1>Attractions#update</h1>
<p>Find me in app/views/attractions/update.html.erb</p>

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title Murray Attractions
    = stylesheet_link_tag 'application'
    = javascript_include_tag 'application'
    = csrf_meta_tags
   
%body
  -if flash[:notice]
    #notice.message= flash[:notice]
  -elsif flash[:warning]
    #warning.message= flash[:warning]
  =  yield
        